name: test-controller-daemons
base: core18
version: '0.1'
summary: test adaemon  controller
description: a daemon controller
  

grade: devel
confinement: strict

apps:
  controlled-1:
    command: bin/controlled-1
    daemon: simple
  start-controlled-1:
    command: bin/start-controlled-1
  stop-controlled-1:
    command: bin/stop-controlled-1
  start:
    command: bin/start
    daemon: simple
    plugs: [ snapd-control ]
  list:
    command: bin/list
    plugs: [ snapd-control ]

parts:
  controlled-1:
    source: controlled-1
    plugin: dump
  start-controlled-1:
    source: start-controlled-1
    plugin: dump
  stop-controlled-1:
    source: stop-controlled-1
    plugin: dump
  snapdapi:
    source: .
    plugin: go
    go-importpath: github.com/knitzsche/test-controller-daemons
    override-build: |
       mkdir -p  ../go/
       export GOPATH=$(cd ../go && pwd)
       GOBIN=$GOPATH/bin
       PKG=github.com/knitzsche/test-controller-daemons
       mkdir -p $GOBIN
       cd $GOPATH/src/$PKG
       go install ./...
       mkdir -p $SNAPCRAFT_PART_INSTALL/bin
       cp $GOBIN/list $SNAPCRAFT_PART_INSTALL/bin/
       cp $GOBIN/start $SNAPCRAFT_PART_INSTALL/bin/
