name: test-controller-daemons
base: core18
version: '0.1'
summary: test adaemon  controller
description: a daemon controller
  

grade: devel
confinement: strict

apps:
  controlled-1:
    command: bin/controlled-1
    daemon: simple
  start-controlled-1:
    command: bin/start-controlled-1
  stop-controlled-1:
    command: bin/stop-controlled-1
  controller:
    command: bin/controller
    daemon: simple
    plugs: [ snapd-control ]
  list:
    command: bin/list
    plugs: [ snapd-control ]

parts:
  controlled-1:
    source: controlled-1
    plugin: dump
  start-controlled-1:
    source: start-controlled-1
    plugin: dump
  stop-controlled-1:
    source: stop-controlled-1
    plugin: dump
  snapdapi:
    source: .
    plugin: go
    go-importpath: github.com/knitzsche/test-controller-daemons
    build-packages: [ gcc ]
