name: test-controller-daemons
base: core18
version: '0.1'
summary: test adaemon  controller
description: a daemon controller
  

grade: devel
confinement: strict

apps:
  controlled-1:
    command: bin/controlled-1
    daemon: simple
  start-controlled-1:
    command: bin/start-controlled-1
  list:
    command: bin/list
    plugs: [ snapd-control ]
  start:
    command: bin/start
    plugs: [ snapd-control ]

parts:
  controlled-1:
    source: controlled-1
    plugin: dump
  start-controlled-1:
    source: start-controlled-1
    plugin: dump
    #go:
    #plugin: nil
    #source-tag: go1.12.1
    #source-depth: 1
  snapdapi:
    source: .
    plugin: go
    go-importpath: github.com/knitzsche/test-controller-daemons
    #go-importpath: github.com/snapcore/snapd
    #go-packages: [github.com/snapcore/snapd/client]
    #source-type: git 
    #after: [ go ]
    override-build: |
       echo "working dir 1 is $(pwd)"
       mkdir -p  ../go/
       #snapcraftctl build
       export GOPATH=$(cd ../go && pwd)
       GOBIN=$GOPATH/bin
       echo "GOBIN 1 is $GOBIN"
       PKG=github.com/knitzsche/test-controller-daemons
       mkdir -p $GOBIN
       cd $GOPATH/src/$PKG
       echo "working dir 2 is $(pwd)"
       go install ./...
       mkdir -p $SNAPCRAFT_PART_INSTALL/bin
       cp $GOBIN/list $SNAPCRAFT_PART_INSTALL/bin/
       cp $GOBIN/start $SNAPCRAFT_PART_INSTALL/bin/
  #list:
    #source: cmd/list/
    #plugin: go
    #go-importpath: github.com/knitzsche/test-controller-daemons
    #source-type: git 
    #after: [ snapdapi ]
