name: test-controlled-daemons
base: core18
version: '0.1'
summary: test a controlled daemon
description: a controlled daemon
  

grade: devel
confinement: strict

apps:
  controlled-1:
    command: bin/controlled-1
    daemon: simple
  start-controlled-1:
    command: bin/start-controlled-1
  #list:
    #command: 

parts:
  controlled-1:
    source: controlled-1
    plugin: dump
  start-controlled-1:
    source: start-controlled-1
    plugin: dump
  snapdapi:
    source: snapdapi
    plugin: go
    go-importpath: github.com/snapcore/snapd/
    source-type: git 
    #  list:
    #source: cmd/list/
    #plugin: go
    #go-importpath: github.com/knitzsche/test-controller-daemons
    #source-type: git 
    #after: [ snapdapi ]
